import { CVData } from '../types';

export const templatePreviewData: Record<string, CVData> = {
    classic: {
        templateId: 'classic',
        themeColor: '#6d54b0',
        personal: {
            firstName: 'Emily',
            lastName: 'Thompson',
            fullName: 'Emily Thompson',
            email: 'emily.thompson@email.com',
            phone: '+1 (555) 234-5678',
            address: '789 Oak Avenue',
            city: 'Boston',
            postcode: '02108',
            country: 'United States',
            birthDate: 'April 22, 1992',
            nationality: 'American',
            drivingLicense: 'Class B',
            linkedin: 'linkedin.com/in/emilythompson',
            website: 'emilythompson.com',
            twitter: '@emilyt',
            title: 'Financial Analyst',
        },
        summary: 'Detail-oriented Financial Analyst with 6+ years of experience in corporate finance and investment analysis. Proven track record in financial modeling, forecasting, and strategic planning.',
        experience: [
            {
                id: 'exp1',
                position: 'Senior Financial Analyst',
                company: 'Global Finance Corp',
                location: 'Boston, MA',
                startDate: 'Jan 2021',
                endDate: '',
                current: true,
                description: 'Lead financial analysis and reporting for $500M portfolio. Developed forecasting models improving accuracy by 25%.',
            },
            {
                id: 'exp2',
                position: 'Financial Analyst',
                company: 'Investment Partners LLC',
                location: 'Boston, MA',
                startDate: 'Jun 2018',
                endDate: 'Dec 2020',
                current: false,
                description: 'Conducted market research and financial analysis for investment decisions.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'MBA in Finance',
                school: 'Boston University',
                location: 'Boston, MA',
                startDate: '2016',
                endDate: '2018',
                description: 'GPA: 3.8/4.0',
            },
        ],
        skills: ['Financial Modeling', 'Excel', 'SQL', 'Tableau', 'Bloomberg Terminal', 'Risk Analysis'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
            { id: 'lang2', language: 'Spanish', proficiency: 'Intermediate' },
        ],
        certifications: [
            { id: 'cert1', name: 'CFA Level II', issuer: 'CFA Institute', date: '2022' },
        ],
        hobbies: [],
    },
    
    modern: {
        templateId: 'modern',
        themeColor: '#2563eb',
        personal: {
            firstName: 'Marcus',
            lastName: 'Chen',
            fullName: 'Marcus Chen',
            email: 'marcus.chen@email.com',
            phone: '+1 (555) 345-6789',
            address: '456 Tech Boulevard',
            city: 'San Jose',
            postcode: '95110',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: 'linkedin.com/in/marcuschen',
            website: 'marcuschen.dev',
            twitter: '@marcusdev',
            title: 'Full Stack Developer',
        },
        summary: 'Innovative Full Stack Developer with 5+ years building scalable web applications. Expert in React, Node.js, and cloud technologies.',
        experience: [
            {
                id: 'exp1',
                position: 'Senior Full Stack Developer',
                company: 'TechStart Inc',
                location: 'San Jose, CA',
                startDate: 'Mar 2021',
                endDate: '',
                current: true,
                description: 'Lead development of microservices architecture serving 2M+ users. Reduced API response time by 40%.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'BS in Computer Science',
                school: 'UC Berkeley',
                location: 'Berkeley, CA',
                startDate: '2015',
                endDate: '2019',
                description: 'Graduated with Honors',
            },
        ],
        skills: ['React', 'Node.js', 'TypeScript', 'AWS', 'Docker', 'MongoDB'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
            { id: 'lang2', language: 'Mandarin', proficiency: 'Native' },
        ],
        certifications: [],
        hobbies: ['Open Source', 'Tech Blogging'],
    },
    
    minimal: {
        templateId: 'minimal',
        themeColor: '#059669',
        personal: {
            firstName: 'Dr. Sarah',
            lastName: 'Williams',
            fullName: 'Dr. Sarah Williams',
            email: 'sarah.williams@university.edu',
            phone: '+1 (555) 456-7890',
            address: '123 Academic Lane',
            city: 'Cambridge',
            postcode: '02138',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: '',
            website: '',
            twitter: '',
            title: 'Associate Professor of Psychology',
        },
        summary: 'Dedicated researcher and educator specializing in cognitive psychology with 10+ years of academic experience.',
        experience: [
            {
                id: 'exp1',
                position: 'Associate Professor',
                company: 'Harvard University',
                location: 'Cambridge, MA',
                startDate: '2019',
                endDate: '',
                current: true,
                description: 'Teaching graduate and undergraduate courses. Published 15+ peer-reviewed articles.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'PhD in Psychology',
                school: 'Stanford University',
                location: 'Stanford, CA',
                startDate: '2012',
                endDate: '2017',
                description: 'Dissertation: Cognitive Processes in Decision Making',
            },
        ],
        skills: ['Research Design', 'Statistical Analysis', 'SPSS', 'R', 'Academic Writing'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
        ],
        certifications: [],
        hobbies: [],
    },
    
    creative: {
        templateId: 'creative',
        themeColor: '#ea580c',
        personal: {
            firstName: 'Isabella',
            lastName: 'Martinez',
            fullName: 'Isabella Martinez',
            email: 'isabella.martinez@design.com',
            phone: '+1 (555) 567-8901',
            address: '789 Design Street',
            city: 'Los Angeles',
            postcode: '90012',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: 'linkedin.com/in/isabellamartinez',
            website: 'isabelladesigns.com',
            twitter: '@isabelladesigns',
            title: 'UX/UI Designer',
        },
        summary: 'Creative UX/UI Designer with 7+ years crafting beautiful, user-centered digital experiences for leading brands.',
        experience: [
            {
                id: 'exp1',
                position: 'Senior UX Designer',
                company: 'Creative Agency LA',
                location: 'Los Angeles, CA',
                startDate: 'Jan 2020',
                endDate: '',
                current: true,
                description: 'Lead design for Fortune 500 clients. Increased user engagement by 60% through redesign initiatives.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'BFA in Graphic Design',
                school: 'Art Center College',
                location: 'Pasadena, CA',
                startDate: '2013',
                endDate: '2017',
                description: 'Dean\'s List',
            },
        ],
        skills: ['Figma', 'Adobe XD', 'Sketch', 'Prototyping', 'User Research', 'Design Systems'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
            { id: 'lang2', language: 'Spanish', proficiency: 'Native' },
        ],
        certifications: [],
        hobbies: ['Photography', 'Art Exhibitions'],
    },
    
    executive: {
        templateId: 'executive',
        themeColor: '#b8860b',
        personal: {
            firstName: 'James',
            lastName: 'Anderson',
            fullName: 'James Anderson',
            email: 'james.anderson@executive.com',
            phone: '+1 (555) 678-9012',
            address: '456 Executive Plaza',
            city: 'New York',
            postcode: '10022',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: 'linkedin.com/in/jamesanderson',
            website: '',
            twitter: '',
            title: 'Chief Technology Officer',
        },
        summary: 'Visionary technology executive with 20+ years leading digital transformation initiatives for Fortune 500 companies.',
        experience: [
            {
                id: 'exp1',
                position: 'Chief Technology Officer',
                company: 'Global Tech Solutions',
                location: 'New York, NY',
                startDate: '2018',
                endDate: '',
                current: true,
                description: 'Lead technology strategy for $2B organization. Oversee 200+ engineering team.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'MBA',
                school: 'Harvard Business School',
                location: 'Boston, MA',
                startDate: '2005',
                endDate: '2007',
                description: 'Baker Scholar',
            },
        ],
        skills: ['Strategic Planning', 'Digital Transformation', 'Team Leadership', 'Cloud Architecture'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
        ],
        certifications: [],
        hobbies: [],
    },
    
    professional: {
        templateId: 'professional',
        themeColor: '#7c3aed',
        personal: {
            firstName: 'Rachel',
            lastName: 'Kim',
            fullName: 'Rachel Kim',
            email: 'rachel.kim@pm.com',
            phone: '+1 (555) 789-0123',
            address: '321 Project Lane',
            city: 'Seattle',
            postcode: '98101',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: 'linkedin.com/in/rachelkim',
            website: '',
            twitter: '',
            title: 'Project Manager',
        },
        summary: 'Results-driven Project Manager with 8+ years delivering complex projects on time and under budget.',
        experience: [
            {
                id: 'exp1',
                position: 'Senior Project Manager',
                company: 'Tech Innovations',
                location: 'Seattle, WA',
                startDate: 'Feb 2019',
                endDate: '',
                current: true,
                description: 'Manage $5M+ projects. Achieved 98% on-time delivery rate.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'BS in Business Administration',
                school: 'University of Washington',
                location: 'Seattle, WA',
                startDate: '2011',
                endDate: '2015',
                description: 'Cum Laude',
            },
        ],
        skills: ['Agile', 'Scrum', 'JIRA', 'MS Project', 'Risk Management', 'Stakeholder Management'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
            { id: 'lang2', language: 'Korean', proficiency: 'Advanced' },
        ],
        certifications: [
            { id: 'cert1', name: 'PMP', issuer: 'PMI', date: '2020' },
        ],
        hobbies: [],
    },
    
    bold: {
        templateId: 'bold',
        themeColor: '#dc2626',
        personal: {
            firstName: 'David',
            lastName: 'Rodriguez',
            fullName: 'David Rodriguez',
            email: 'david.rodriguez@marketing.com',
            phone: '+1 (555) 890-1234',
            address: '654 Marketing Ave',
            city: 'Miami',
            postcode: '33101',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: 'linkedin.com/in/davidrodriguez',
            website: 'davidrodriguez.com',
            twitter: '@davidmktg',
            title: 'Marketing Director',
        },
        summary: 'Dynamic Marketing Director with 10+ years driving brand growth and digital marketing strategies.',
        experience: [
            {
                id: 'exp1',
                position: 'Marketing Director',
                company: 'Brand Builders Inc',
                location: 'Miami, FL',
                startDate: 'Jan 2020',
                endDate: '',
                current: true,
                description: 'Lead marketing team of 15. Increased brand awareness by 150% and revenue by $10M.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'MBA in Marketing',
                school: 'University of Miami',
                location: 'Miami, FL',
                startDate: '2010',
                endDate: '2012',
                description: 'Marketing Excellence Award',
            },
        ],
        skills: ['Digital Marketing', 'SEO/SEM', 'Social Media', 'Analytics', 'Brand Strategy', 'Content Marketing'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
            { id: 'lang2', language: 'Spanish', proficiency: 'Native' },
        ],
        certifications: [],
        hobbies: ['Content Creation', 'Public Speaking'],
    },
    
    timeline: {
        templateId: 'timeline',
        themeColor: '#0d9488',
        personal: {
            firstName: 'Alexandra',
            lastName: 'Patel',
            fullName: 'Alexandra Patel',
            email: 'alexandra.patel@tech.com',
            phone: '+1 (555) 901-2345',
            address: '987 Innovation Drive',
            city: 'Austin',
            postcode: '78701',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: 'linkedin.com/in/alexandrapatel',
            website: 'alexpatel.tech',
            twitter: '@alexpatel',
            title: 'Software Engineering Manager',
        },
        summary: 'Experienced Engineering Manager with 12+ years building high-performing teams and delivering innovative software solutions.',
        experience: [
            {
                id: 'exp1',
                position: 'Engineering Manager',
                company: 'Tech Giants',
                location: 'Austin, TX',
                startDate: 'Mar 2020',
                endDate: '',
                current: true,
                description: 'Lead team of 20 engineers. Delivered 5 major product releases.',
            },
            {
                id: 'exp2',
                position: 'Senior Software Engineer',
                company: 'StartupXYZ',
                location: 'Austin, TX',
                startDate: 'Jan 2016',
                endDate: 'Feb 2020',
                current: false,
                description: 'Built scalable backend systems. Mentored junior developers.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'MS in Computer Science',
                school: 'UT Austin',
                location: 'Austin, TX',
                startDate: '2010',
                endDate: '2012',
                description: 'Focus on Distributed Systems',
            },
        ],
        skills: ['Python', 'Java', 'Kubernetes', 'Team Leadership', 'System Design', 'Agile'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
        ],
        certifications: [],
        hobbies: ['Mentoring', 'Tech Conferences'],
    },
    
    'two-column': {
        templateId: 'two-column',
        themeColor: '#1e3a8a',
        personal: {
            firstName: 'Michael',
            lastName: 'Foster',
            fullName: 'Michael Foster',
            email: 'michael.foster@consulting.com',
            phone: '+1 (555) 012-3456',
            address: '147 Consulting Plaza',
            city: 'Chicago',
            postcode: '60601',
            country: 'United States',
            birthDate: 'June 15, 1985',
            nationality: 'American',
            drivingLicense: 'Class C',
            linkedin: 'linkedin.com/in/michaelfoster',
            website: 'michaelfoster.com',
            twitter: '',
            title: 'Management Consultant',
        },
        summary: 'Strategic Management Consultant with 15+ years advising Fortune 500 companies on operational excellence and growth strategies.',
        experience: [
            {
                id: 'exp1',
                position: 'Senior Consultant',
                company: 'Global Consulting Group',
                location: 'Chicago, IL',
                startDate: 'Jan 2015',
                endDate: '',
                current: true,
                description: 'Lead consulting engagements for C-suite clients. Delivered $50M+ in cost savings.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'MBA',
                school: 'University of Chicago Booth',
                location: 'Chicago, IL',
                startDate: '2008',
                endDate: '2010',
                description: 'Honors Graduate',
            },
        ],
        skills: ['Strategy', 'Operations', 'Change Management', 'Financial Analysis', 'Stakeholder Engagement'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
            { id: 'lang2', language: 'French', proficiency: 'Advanced' },
        ],
        certifications: [
            { id: 'cert1', name: 'Six Sigma Black Belt', issuer: 'ASQ', date: '2018' },
        ],
        hobbies: [],
    },
    
    'minimalist-pro': {
        templateId: 'minimalist-pro',
        themeColor: '#374151',
        personal: {
            firstName: 'Victoria',
            lastName: 'Bennett',
            fullName: 'Victoria Bennett',
            email: 'victoria.bennett@executive.com',
            phone: '+1 (555) 123-4567',
            address: '258 Executive Row',
            city: 'San Francisco',
            postcode: '94102',
            country: 'United States',
            birthDate: '',
            nationality: '',
            drivingLicense: '',
            linkedin: 'linkedin.com/in/victoriabennett',
            website: '',
            twitter: '',
            title: 'Chief Operating Officer',
        },
        summary: 'Accomplished executive leader with 18+ years driving operational excellence and strategic growth for technology companies.',
        experience: [
            {
                id: 'exp1',
                position: 'Chief Operating Officer',
                company: 'Innovation Labs',
                location: 'San Francisco, CA',
                startDate: '2019',
                endDate: '',
                current: true,
                description: 'Oversee all operations for $500M company. Led successful IPO in 2022.',
            },
        ],
        education: [
            {
                id: 'edu1',
                degree: 'MBA',
                school: 'Stanford GSB',
                location: 'Stanford, CA',
                startDate: '2003',
                endDate: '2005',
                description: 'Arjay Miller Scholar',
            },
        ],
        skills: ['Operations Management', 'Strategic Planning', 'P&L Management', 'M&A', 'Board Relations'],
        languages: [
            { id: 'lang1', language: 'English', proficiency: 'Native' },
        ],
        certifications: [],
        hobbies: [],
    },
};
