import { CVData } from '../types';

export const minimalTestData: CVData = {
    templateId: 'modern',
    themeColor: '#6d54b0',
    personal: {
        firstName: 'John',
        lastName: 'Doe',
        fullName: 'John Doe',
        email: 'john@example.com',
        phone: '+1 555-0100',
        address: '',
        city: '',
        postcode: '',
        country: '',
        birthDate: '',
        nationality: '',
        drivingLicense: '',
        linkedin: '',
        website: '',
        twitter: '',
        title: 'Software Developer',
        photo: undefined,
    },
    summary: '',
    experience: [],
    education: [],
    skills: [],
    languages: [],
    certifications: [],
    hobbies: [],
};

export const maximalTestData: CVData = {
    templateId: 'modern',
    themeColor: '#6d54b0',
    personal: {
        firstName: 'Alexandra',
        lastName: 'Rodriguez',
        fullName: 'Alexandra Rodriguez',
        email: 'alexandra.rodriguez@email.com',
        phone: '+1 (555) 987-6543',
        address: '456 Innovation Drive',
        city: 'San Francisco',
        postcode: '94105',
        country: 'United States',
        birthDate: 'January 10, 1988',
        nationality: 'American',
        drivingLicense: 'Class A',
        linkedin: 'linkedin.com/in/alexrodriguez',
        website: 'alexrodriguez.tech',
        twitter: '@alextech',
        title: 'Senior Product Manager & UX Strategist',
        photo: undefined,
    },
    summary: 'Innovative Product Manager with 12+ years of experience leading cross-functional teams to deliver user-centric digital products. Proven track record of driving product strategy, increasing user engagement by 300%, and managing $50M+ product portfolios. Expert in agile methodologies, data-driven decision making, and stakeholder management. Passionate about creating seamless user experiences that solve real-world problems.',
    experience: [
        {
            id: 'exp1',
            position: 'Senior Product Manager',
            company: 'TechGiant Inc',
            location: 'San Francisco, CA',
            startDate: 'Jan 2020',
            endDate: '',
            current: true,
            description: 'Lead product strategy for flagship SaaS platform serving 5M+ users. Increased user retention by 45% through data-driven feature prioritization. Manage cross-functional team of 15 engineers, designers, and analysts. Successfully launched 3 major product releases, generating $20M in additional revenue.',
        },
        {
            id: 'exp2',
            position: 'Product Manager',
            company: 'StartupXYZ',
            location: 'San Francisco, CA',
            startDate: 'Mar 2017',
            endDate: 'Dec 2019',
            current: false,
            description: 'Drove product development from concept to launch for mobile application with 1M+ downloads. Conducted user research with 500+ participants to inform product roadmap. Collaborated with engineering team to implement agile development processes, reducing time-to-market by 40%.',
        },
        {
            id: 'exp3',
            position: 'Associate Product Manager',
            company: 'Digital Solutions Corp',
            location: 'Seattle, WA',
            startDate: 'Jun 2015',
            endDate: 'Feb 2017',
            current: false,
            description: 'Supported senior PM in managing e-commerce platform features. Analyzed user behavior data to identify optimization opportunities. Created product requirements documents and user stories for development team.',
        },
        {
            id: 'exp4',
            position: 'Business Analyst',
            company: 'Consulting Partners LLC',
            location: 'Seattle, WA',
            startDate: 'Aug 2012',
            endDate: 'May 2015',
            current: false,
            description: 'Conducted market research and competitive analysis for Fortune 500 clients. Developed business cases and ROI models for new product initiatives. Facilitated stakeholder workshops to gather requirements.',
        },
        {
            id: 'exp5',
            position: 'Junior Analyst',
            company: 'Tech Innovations',
            location: 'Portland, OR',
            startDate: 'Jun 2010',
            endDate: 'Jul 2012',
            current: false,
            description: 'Supported data analysis and reporting for product teams. Created dashboards and visualizations using Tableau. Assisted in user testing sessions and compiled feedback reports.',
        },
    ],
    education: [
        {
            id: 'edu1',
            degree: 'Master of Business Administration (MBA)',
            school: 'Stanford Graduate School of Business',
            location: 'Stanford, CA',
            startDate: '2013',
            endDate: '2015',
            description: 'Concentration in Technology Management and Entrepreneurship. GPA: 3.9/4.0',
            hideDates: false,
            extraInfo: 'Dean\'s List, Recipient of Merit Scholarship',
        },
        {
            id: 'edu2',
            degree: 'Bachelor of Science in Computer Science',
            school: 'University of Washington',
            location: 'Seattle, WA',
            startDate: '2006',
            endDate: '2010',
            description: 'Minor in Business Administration. Graduated Summa Cum Laude.',
            hideDates: false,
            extraInfo: 'President of Women in Tech Club, Hackathon Winner 2009',
        },
        {
            id: 'edu3',
            degree: 'Certificate in UX Design',
            school: 'Nielsen Norman Group',
            location: 'Online',
            startDate: '2016',
            endDate: '2016',
            description: 'Intensive program covering user research, interaction design, and usability testing.',
            hideDates: false,
            extraInfo: '',
        },
    ],
    skills: [
        'Product Strategy',
        'Agile/Scrum',
        'User Research',
        'Data Analysis',
        'A/B Testing',
        'SQL',
        'Python',
        'Tableau',
        'Figma',
        'JIRA',
        'Roadmap Planning',
        'Stakeholder Management',
        'Market Research',
        'Competitive Analysis',
        'Product Analytics',
        'User Stories',
        'Wireframing',
        'API Integration',
        'Go-to-Market Strategy',
        'KPI Tracking',
    ],
    languages: [
        { id: 'lang1', language: 'English', proficiency: 'Native' },
        { id: 'lang2', language: 'Spanish', proficiency: 'Advanced' },
        { id: 'lang3', language: 'French', proficiency: 'Intermediate' },
        { id: 'lang4', language: 'Mandarin', proficiency: 'Basic' },
    ],
    certifications: [
        {
            id: 'cert1',
            name: 'Certified Scrum Product Owner (CSPO)',
            issuer: 'Scrum Alliance',
            date: '2021',
            credentialId: 'CSPO-2021-98765',
        },
        {
            id: 'cert2',
            name: 'Product Management Certificate',
            issuer: 'Product School',
            date: '2019',
            credentialId: 'PM-2019-54321',
        },
        {
            id: 'cert3',
            name: 'Google Analytics Certification',
            issuer: 'Google',
            date: '2020',
            credentialId: 'GA-2020-11223',
        },
        {
            id: 'cert4',
            name: 'AWS Cloud Practitioner',
            issuer: 'Amazon Web Services',
            date: '2022',
            credentialId: 'AWS-CP-2022-44556',
        },
    ],
    hobbies: [
        'Tech Blogging',
        'Mentoring',
        'Photography',
        'Yoga',
        'Traveling',
    ],
};

export const techDeveloperData: CVData = {
    ...minimalTestData,
    personal: {
        ...minimalTestData.personal,
        fullName: 'Alex Chen',
        title: 'Full Stack Developer',
    },
    experience: [
        {
            id: 'exp1',
            position: 'Senior Full Stack Developer',
            company: 'Tech Startup',
            location: 'Remote',
            startDate: 'Jan 2021',
            endDate: '',
            current: true,
            description: 'Building scalable web applications using React, Node.js, and AWS.',
        },
    ],
    skills: ['JavaScript', 'React', 'Node.js', 'TypeScript', 'AWS', 'Docker'],
};

export const creativeDesignerData: CVData = {
    ...minimalTestData,
    personal: {
        ...minimalTestData.personal,
        fullName: 'Maria Garcia',
        title: 'UX/UI Designer',
    },
    experience: [
        {
            id: 'exp1',
            position: 'Senior UX Designer',
            company: 'Design Agency',
            location: 'New York, NY',
            startDate: 'Mar 2019',
            endDate: '',
            current: true,
            description: 'Creating user-centered designs for mobile and web applications.',
        },
    ],
    skills: ['Figma', 'Adobe XD', 'User Research', 'Prototyping', 'Design Systems'],
};
